In [1]:
import pandas as pd
import folium
import time
from geopy.geocoders import Nominatim

In [2]:
df = pd.read_csv('../../data/trade_apt_api_2023_address.txt', sep="\t")
df

,기준년월,지역명,지역코드,법정동,아파트,거래금액,년,월,일,건축년도,전용면적,지번,층
0,202306,종로구,11110,사직동,광화문스페이스본(101동~105동),"138,000",2023,6,9,2008,95.880,9,9
1,202306,종로구,11110,사직동,광화문스페이스본(101동~105동),"170,000",2023,6,10,2008,146.920,9,8
2,202306,종로구,11110,사직동,사직아파트,"84,000",2023,6,12,1970,116.230,1-8,6
3,202306,종로구,11110,당주동,롯데미도파광화문빌딩,"93,000",2023,6,20,1981,149.950,145,9
4,202306,종로구,11110,신문로2가,디팰리스,"408,000",2023,6,24,2020,148.111,171,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2297,202201,강남구,11680,도곡동,현대비젼21,"50,000",2022,1,14,1999,35.480,467-19,20
2298,202201,강남구,11680,도곡동,삼성,"220,000",2022,1,15,1994,84.910,161,5
2299,202201,강남구,11680,도곡동,SK허브프리모,"37,400",2022,1,18,2006,33.800,953-1,8
2300,202201,강남구,11680,도곡동,한신(개포),"281,000",2022,1,23,1985,83.860,464,5
2301,202201,강남구,11680,도곡동,타워팰리스3,"420,000",2022,1,27,2004,163.567,467-29,42

In [3]:
df['주소'] = '서울시 '+df['지역명']+' '+df['법정동']+' '+df['지번']
print(df['주소'])

0            서울시 종로구  사직동 9
1            서울시 종로구  사직동 9
2          서울시 종로구  사직동 1-8
3          서울시 종로구  당주동 145
4        서울시 종로구  신문로2가 171
               ...
2297    서울시 강남구  도곡동 467-19
2298       서울시 강남구  도곡동 161
2299     서울시 강남구  도곡동 953-1
2300       서울시 강남구  도곡동 464
2301    서울시 강남구  도곡동 467-29
Name: 주소, Length: 2302, dtype: str

In [4]:
df

,기준년월,지역명,지역코드,법정동,아파트,거래금액,년,월,일,건축년도,전용면적,지번,층,주소
0,202306,종로구,11110,사직동,광화문스페이스본(101동~105동),"138,000",2023,6,9,2008,95.880,9,9,서울시 종로구 사직동 9
1,202306,종로구,11110,사직동,광화문스페이스본(101동~105동),"170,000",2023,6,10,2008,146.920,9,8,서울시 종로구 사직동 9
2,202306,종로구,11110,사직동,사직아파트,"84,000",2023,6,12,1970,116.230,1-8,6,서울시 종로구 사직동 1-8
3,202306,종로구,11110,당주동,롯데미도파광화문빌딩,"93,000",2023,6,20,1981,149.950,145,9,서울시 종로구 당주동 145
4,202306,종로구,11110,신문로2가,디팰리스,"408,000",2023,6,24,2020,148.111,171,10,서울시 종로구 신문로2가 171
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2297,202201,강남구,11680,도곡동,현대비젼21,"50,000",2022,1,14,1999,35.480,467-19,20,서울시 강남구 도곡동 467-19
2298,202201,강남구,11680,도곡동,삼성,"220,000",2022,1,15,1994,84.910,161,5,서울시 강남구 도곡동 161
2299,202201,강남구,11680,도곡동,SK허브프리모,"37,400",2022,1,18,2006,33.800,953-1,8,서울시 강남구 도곡동 953-1
2300,202201,강남구,11680,도곡동,한신(개포),"281,000",2022,1,23,1985,83.860,464,5,서울시 강남구 도곡동 464
2301,202201,강남구,11680,도곡동,타워팰리스3,"420,000",2022,1,27,2004,163.567,467-29,42,서울시 강남구 도곡동 467-29

In [7]:
geo_local = Nominatim(user_agent='new-apt-map-trainer')
def geocoding(address):
  try:
    geo = geo_local.geocode(address)
    if geo is None:
      return None, None
    return geo.latitude, geo.longitude
  except:
    return None, None

In [10]:
N = 30
#N = 3
sample = df.head( N ).copy()
print(sample)

      기준년월  지역명   지역코드     법정동                  아파트          거래금액     년  월  \
0   202306  종로구  11110     사직동  광화문스페이스본(101동~105동)       138,000  2023  6
1   202306  종로구  11110     사직동  광화문스페이스본(101동~105동)       170,000  2023  6
2   202306  종로구  11110     사직동                사직아파트        84,000  2023  6
3   202306  종로구  11110     당주동           롯데미도파광화문빌딩        93,000  2023  6
4   202306  종로구  11110   신문로2가                 디팰리스       408,000  2023  6
5   202306  종로구  11110     익선동               운현신화타워        64,500  2023  6
6   202306  종로구  11110     익선동               현대뜨레비앙        40,000  2023  6
7   202306  종로구  11110     효제동              포레스트힐시티        17,300  2023  6
8   202306  종로구  11110     충신동                 CS타워        15,400  2023  6
9   202306  종로구  11110    명륜1가                  렉스빌        60,000  2023  6
10  202306  종로구  11110    명륜2가                  아남2       136,000  2023  6
11  202306  종로구  11110     숭인동            숭인한양LEEPS        12,000  2023  6
12  202306  종로구  11110     숭인동              롯데캐슬천지인       120,000  2023  6
13  202306  종로구  11110     숭인동                 숭인상가        65,000  2023  6
14  202306  종로구  11110      평동           경희궁자이(3단지)       280,000  2023  6
15  202306  종로구  11110     홍파동           경희궁자이(2단지)       188,000  2023  6
16  202306  종로구  11110     홍파동           경희궁자이(2단지)       270,000  2023  6
17  202306  종로구  11110     홍파동           경희궁자이(2단지)       182,500  2023  6
18  202306  종로구  11110     구기동                 마운틴뷰        56,000  2023  6
19  202306  종로구  11110     무악동              경희궁롯데캐슬       116,500  2023  6
20  202306  종로구  11110     무악동              경희궁롯데캐슬       114,000  2023  6
21  202306  종로구  11110     무악동                   현대       125,900  2023  6
22  202306  종로구  11110     무악동              인왕산아이파크       130,000  2023  6
23  202306  종로구  11110     무악동              인왕산아이파크       158,000  2023  6
24  202306  종로구  11110     무악동              경희궁롯데캐슬       141,000  2023  6
25  202306  종로구  11110     무악동                   현대        79,900  2023  6
26  202306  종로구  11110     무악동                   현대       108,900  2023  6
27  202306  종로구  11110     무악동                   현대       142,000  2023  6
28  202306  종로구  11110     무악동            인왕산2차아이파크       115,500  2023  6
29  202306  종로구  11110     무악동              인왕산아이파크       129,500  2023  6

     일  건축년도      전용면적      지번   층                   주소
0    9  2008   95.8800       9   9       서울시 종로구  사직동 9
1   10  2008  146.9200       9   8       서울시 종로구  사직동 9
2   12  1970  116.2300     1-8   6     서울시 종로구  사직동 1-8
3   20  1981  149.9500     145   9     서울시 종로구  당주동 145
4   24  2020  148.1110     171  10   서울시 종로구  신문로2가 171
5   24  1998   50.3100    30-6  14    서울시 종로구  익선동 30-6
6   27  2003   46.6400      55   3      서울시 종로구  익선동 55
7    6  2017   15.8790    65-2   5    서울시 종로구  효제동 65-2
8   22  2011   22.1700    62-2   5    서울시 종로구  충신동 62-2
9   25  2006   80.5000      19   6     서울시 종로구  명륜1가 19
10  14  1996  114.3600     236   7    서울시 종로구  명륜2가 236
11   1  2014   12.7800  1421-2  11  서울시 종로구  숭인동 1421-2
12  24  2004  111.7300      76  28      서울시 종로구  숭인동 76
13  27  1979   78.7500  204-11   7  서울시 종로구  숭인동 204-11
14  22  2017  116.9383     233   9      서울시 종로구  평동 233
15   8  2017   84.9443     199  14     서울시 종로구  홍파동 199
16  14  2017  116.9862     199  20     서울시 종로구  홍파동 199
17  22  2017   84.8359     199  10     서울시 종로구  홍파동 199
18   6  2019   76.6600   125-5   1   서울시 종로구  구기동 125-5
19   5  2019   59.6737      89   4      서울시 종로구  무악동 89
20   7  2019   59.6737      89   2      서울시 종로구  무악동 89
21   9  2000  114.9000      82   3      서울시 종로구  무악동 82
22  10  2008   84.8580      60  15      서울시 종로구  무악동 60
23  10  2008  114.9310      60  10      서울시 종로구  무악동 60
24  14  2019   84.8792      89   8      서울시 종로구  무악동 89
25  19  2000   60.0000      82   3      서울시 종로구  무악동 82
26  19  2000   84.9200      82   5      서울시 종로구  무악동 82
27  20  2000  114.9000      82  17      서울시 종로구  무악동 82
28  24  2015   84.2395      88   6      서울시 종로구  무악동 88
29  30  2008   84.8580      60   7      서울시 종로구  무악동 60

In [11]:
sample

,기준년월,지역명,지역코드,법정동,아파트,거래금액,년,월,일,건축년도,전용면적,지번,층,주소
0,202306,종로구,11110,사직동,광화문스페이스본(101동~105동),"138,000",2023,6,9,2008,95.8800,9,9,서울시 종로구 사직동 9
1,202306,종로구,11110,사직동,광화문스페이스본(101동~105동),"170,000",2023,6,10,2008,146.9200,9,8,서울시 종로구 사직동 9
2,202306,종로구,11110,사직동,사직아파트,"84,000",2023,6,12,1970,116.2300,1-8,6,서울시 종로구 사직동 1-8
3,202306,종로구,11110,당주동,롯데미도파광화문빌딩,"93,000",2023,6,20,1981,149.9500,145,9,서울시 종로구 당주동 145
4,202306,종로구,11110,신문로2가,디팰리스,"408,000",2023,6,24,2020,148.1110,171,10,서울시 종로구 신문로2가 171
5,202306,종로구,11110,익선동,운현신화타워,"64,500",2023,6,24,1998,50.3100,30-6,14,서울시 종로구 익선동 30-6
6,202306,종로구,11110,익선동,현대뜨레비앙,"40,000",2023,6,27,2003,46.6400,55,3,서울시 종로구 익선동 55
7,202306,종로구,11110,효제동,포레스트힐시티,"17,300",2023,6,6,2017,15.8790,65-2,5,서울시 종로구 효제동 65-2
8,202306,종로구,11110,충신동,CS타워,"15,400",2023,6,22,2011,22.1700,62-2,5,서울시 종로구 충신동 62-2
9,202306,종로구,11110,명륜1가,렉스빌,"60,000",2023,6,25,2006,80.5000,19,6,서울시 종로구 명륜1가 19
10,202306,종로구,11110,명륜2가,아남2,"136,000",2023,6,14,1996,114.3600,236,7,서울시 종로구 명륜2가 236
11,202306,종로구,11110,숭인동,숭인한양LEEPS,"12,000",2023,6,1,2014,12.7800,1421-2,11,서울시 종로구 숭인동 1421-2
12,202306,종로구,11110,숭인동,롯데캐슬천지인,"120,000",2023,6,24,2004,111.7300,76,28,서울시 종로구 숭인동 76
13,202306,종로구,11110,숭인동,숭인상가,"65,000",2023,6,27,1979,78.7500,204-11,7,서울시 종로구 숭인동 204-11
14,202306,종로구,11110,평동,경희궁자이(3단지),"280,000",2023,6,22,2017,116.9383,233,9,서울시 종로구 평동 233
15,202306,종로구,11110,홍파동,경희궁자이(2단지),"188,000",2023,6,8,2017,84.9443,199,14,서울시 종로구 홍파동 199
16,202306,종로구,11110,홍파동,경희궁자이(2단지),"270,000",2023,6,14,2017,116.9862,199,20,서울시 종로구 홍파동 199
17,202306,종로구,11110,홍파동,경희궁자이(2단지),"182,500",2023,6,22,2017,84.8359,199,10,서울시 종로구 홍파동 199
18,202306,종로구,11110,구기동,마운틴뷰,"56,000",2023,6,6,2019,76.6600,125-5,1,서울시 종로구 구기동 125-5
19,202306,종로구,11110,무악동,경희궁롯데캐슬,"116,500",2023,6,5,2019,59.6737,89,4,서울시 종로구 무악동 89
20,202306,종로구,11110,무악동,경희궁롯데캐슬,"114,000",2023,6,7,2019,59.6737,89,2,서울시 종로구 무악동 89
21,202306,종로구,11110,무악동,현대,"125,900",2023,6,9,2000,114.9000,82,3,서울시 종로구 무악동 82
22,202306,종로구,11110,무악동,인왕산아이파크,"130,000",2023,6,10,2008,84.8580,60,15,서울시 종로구 무악동 60
23,202306,종로구,11110,무악동,인왕산아이파크,"158,000",2023,6,10,2008,114.9310,60,10,서울시 종로구 무악동 60
24,202306,종로구,11110,무악동,경희궁롯데캐슬,"141,000",2023,6,14,2019,84.8792,89,8,서울시 종로구 무악동 89
25,202306,종로구,11110,무악동,현대,"79,900",2023,6,19,2000,60.0000,82,3,서울시 종로구 무악동 82
26,202306,종로구,11110,무악동,현대,"108,900",2023,6,19,2000,84.9200,82,5,서울시 종로구 무악동 82
27,202306,종로구,11110,무악동,현대,"142,000",2023,6,20,2000,114.9000,82,17,서울시 종로구 무악동 82
28,202306,종로구,11110,무악동,인왕산2차아이파크,"115,500",2023,6,24,2015,84.2395,88,6,서울시 종로구 무악동 88
29,202306,종로구,11110,무악동,인왕산아이파크,"129,500",2023,6,30,2008,84.8580,60,7,서울시 종로구 무악동 60

In [13]:
for i, row in sample.iterrows():
  address = row['주소']
  time.sleep(1)
  lat, lng = geocoding(address)
  print(f'위도: {lat}, 경도: {lng}')

위도: None, 경도: None
위도: None, 경도: None
위도: None, 경도: None
위도: None, 경도: None
위도: None, 경도: None
위도: None, 경도: None
위도: None, 경도: None
위도: None, 경도: None
위도: None, 경도: None
위도: None, 경도: None
위도: None, 경도: None
위도: None, 경도: None
위도: None, 경도: None
위도: None, 경도: None
위도: None, 경도: None
위도: None, 경도: None
위도: None, 경도: None
위도: None, 경도: None
위도: None, 경도: None
위도: None, 경도: None
위도: None, 경도: None
위도: None, 경도: None
위도: None, 경도: None
위도: None, 경도: None
위도: None, 경도: None
위도: None, 경도: None
위도: None, 경도: None
위도: None, 경도: None
위도: None, 경도: None
위도: None, 경도: None

In [ ]:
#lat = 36.763718
#lng = 127.28194050
#m = folium.Map(location=[lat, lng], zoom_start = 15, titles='OpenStreetMap')

In [ ]:
#folium.Marker(
    #[lat, lng]
    #, popup="다른정보"
    #, tooltip='풍선도움말'
    #, icon=folium.Icon(color='red', icon='glyphicon-heart')   #  https://getbootstrap.com/docs/3.3/components
    # , icon=folium.Icon(color='red', icon='glyphicon glyphicon-ok')
  #).add_to(m)