### 결측치 처리하기

In [71]:
#STEP1 - importing the libraries
import pandas as pd
import numpy as np

In [72]:
#STEP2 - importing the dataset
df = pd.read_csv("../data/Data.csv")
# 변수 X는 독립변수 불러오기 - iloc
X = df.iloc[:,:-1].values
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [73]:
# 변수 y는 종속변수를 불러오기 - iloc
y = df.iloc[:,-1].to_numpy()
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No',
       'Yes                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       '],
      dtype=object)

In [74]:
df.describe()

             Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

```txt
Missing Data처리
NaN(Not a Number): null과 유사한 개념
1) isna() 또는 isnull(): 주어진 컬럼 값들이 NaN인지 True/False 값을 반환
2) fillna():NaN데이터 찾아서 value지정된 값으로 변환
- df.fillna(value='값', inplace=True)
3) dropna(): 행 데이터를 기준으로 NaN값이 포함된 데이터를 제거
- df.dropna(how='all'): 행의 모든 값이 NaN인 행 데이터 제거
- df.dropna(how='any'): 행 데이터 중 하나라도 NaN이면 해당 행만 제거
- 원본 데이터는 변경되지 않으므로 변경하고 싶다면 inplace=True옵션 추가
```

In [75]:
df.fillna(value=df["Salary"].mean())

,Country,Age,Salary,Purchased
0,France,44.000000,72000.000000,No
1,Spain,27.000000,48000.000000,Yes
2,Germany,30.000000,54000.000000,No
3,Spain,38.000000,61000.000000,No
4,Germany,40.000000,63777.777778,Yes
5,France,35.000000,58000.000000,Yes
6,Spain,63777.777778,52000.000000,No
7,France,48.000000,79000.000000,Yes
8,Germany,50.000000,83000.000000,No
9,France,37.000000,67000.000000,Yes ...

```txt
문제제기
Age평균으로 결측처리하기, Salary평균으로 각기 다르게 처리가 안됨.
해결방법
scikit-learn제공하는 SimpleImputer객체를 활용하여 해결하기.
언제 사용하나요?
결측치가 있는 데이터셋을 머신러닝 모델에 입력하기 전에 전처리할 때 사용함.
머신러닝 모델은 자체로 결측치를 처리할 수 없다.
```

In [76]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\kosmo\appdata\local\programs\python\python312\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\kosmo\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (2.4.2)
Requirement already satisfied: scipy>=1.10.0 in c:\users\kosmo\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\kosmo\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\kosmo\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [77]:
from sklearn.impute import SimpleImputer
# strategy="mean": 결측치(NaN)를 해당 열의 평균으로 채움(mean, mos_frequent 등도 가능)
imputer = SimpleImputer(strategy="mean")              # 평균으로 대체하기
#imputer = SimpleImputer(strategy="median")           # 중앙값으로 대채하기. 평균과 중앙값이 반드시 일치하는 건 아님
#imputer = SimpleImputer(strategy="most_frequent")    # 최빈값으로 대체하기
#imputer = SimpleImputer(strategy="constant", fill_value=100)    # 특정값으로 대체하기
X[:, 1:3] = imputer.fit_transform(X[: , 1:3])

print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]

In [ ]:
# X[:, 1:3] : 2차원 배열(행 X열 ) 슬라이싱
# [:, 1:3]
# 맨 앞 콜론( : )의 경우  행은 전부 선택됨( 즉 모든 행이라는 뜻임 )
# 두번째는 열 인덱스 1 이상 3미만 -> 2번째 열, 3번째 열 ( 총 2개 열 출력함)
print(X[:, 1:3])

[[44.0 72000.0]
 [27.0 48000.0]
 [30.0 54000.0]
 [38.0 61000.0]
 [40.0 63777.77777777778]
 [35.0 58000.0]
 [38.77777777777778 52000.0]
 [48.0 79000.0]
 [50.0 83000.0]
 [37.0 67000.0]]