### Pandas
#### 판다스란?
```txt
패널 데이터 와 Python데이터 분석의 이름을 따서 명명
고수준 자료구조 제공.
Numpy기반에서 개발되어 Numpy사용하는 애플리케이션에 쉽게 적용
```
#### 제공 기능
```txt
통합된 시계열 기능
시계열 데이터와 비시계열 데이터를 함께 다룰 수 있는 통합 자료구조
누락된 데이터를 유연하게 처리할 수 있다.
SQL같은 데이터베이스 처럼 데이터 합치고 관계 연산을 수행하는 기능
```

#### Pandas의 주요 구성 요소 : Series, DataFrame, Index
```txt
Series - 1개 컬럼 값만으로 1차원 데이터셋(Set:집합)
DataFrame - column x row 2차원 데이터 셋
Index - Series와 DataFrame의 고유한 Key값
```

#### Pandas의 주요 함수
```txt
데이터 로드 및 저장 : read_csv(), read_html(), to_csv() 
DataFrame 데이터 확인 : df.shape, df.info(), df.columns, df.head(), df.tail()
각 컬럼마다 Null개수 확인 : df.isnull().sum() 
특정 column / row 삭제 : 
- df = df.drop(['column'], axis=1)
- df = df.drop(['row'])
```

In [ ]:
# %pip install pandas

Requirement already satisfied: pandas in c:\users\kosmo\appdata\local\programs\python\python312\lib\site-packages (3.0.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kosmo\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kosmo\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\kosmo\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\kosmo\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Series 구조

In [2]:
import pandas as pd

In [3]:
# Series 생성
se = pd.Series([1,2,3,4,5])
se

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
# 특정 값 추출 : values, index
print(se[0]) 
print(se[3])

1
4

In [5]:
se[len(se)-1]

np.int64(5)

In [6]:
se.index

RangeIndex(start=0, stop=5, step=1)

In [7]:
se.values # Series안에 Numpy가 포함되어 있음

array([1, 2, 3, 4, 5])

In [8]:
## index 변경
se.index = ['a', 'b', 'c', 'd', 'e']
se

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [12]:
print(se['a'])  # 1
print(se['d'])  # 4

1
4

In [10]:
# index 이름 명시하여 Series 생성하기
# index가 순서값은 아니다
se2 = pd.Series([1, 2, 3], index=['값1', '값2', '값3']) 
se2

값1    1
값2    2
값3    3
dtype: int64

In [11]:
se2['값2']

np.int64(2)

In [12]:
se3 = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e']) 
se3

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [13]:
se3 > 2

a    False
b    False
c     True
d     True
e     True
dtype: bool

In [14]:
se[se > 2]

c    3
d    4
e    5
dtype: int64

In [17]:
se[-(se > 2)]

a    1
b    2
dtype: int64

#### DataFrame(데이터프레임)
Pandas에서 행과 열을 가지는 자료구조<br>
데이터프레임은 2차원이므로 행 방향 인덱스( index )와 열 방향 인덱스 ( columlns ) 가 존재<br>
데이터프레임 - 열( columns )까지 추가되어 열, 인덱스, 값으로 구성<br>

- Series: 인덱스와 값으로만 구성<br>

In [18]:
#DataFrame생성
data = {
  'name': ['Lee', 'Park', 'Kim'],
  'score': [100, 80, 90],
  'grade': ['A', 'B', 'A']
}
# import pandas as pd
df = pd.DataFrame(data)
df

   name  score grade
0   Lee    100     A
1  Park     80     B
2   Kim     90     A

In [19]:
print(df)
display(df)

   name  score grade
0   Lee    100     A
1  Park     80     B
2   Kim     90     A

   name  score grade
0   Lee    100     A
1  Park     80     B
2   Kim     90     A

In [20]:
# 컬럼 순서 지정하기
data = {
  'name': ['Lee', 'Park', 'Kim'],
  'score': [100, 80, 90],
  'grade': ['A', 'B', 'A']
}
# import pandas as pd
df = pd.DataFrame(data, columns=['name', 'grade', 'score'])
df

   name grade  score
0   Lee     A    100
1  Park     B     80
2   Kim     A     90

In [21]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [22]:
df.values

array([['Lee', 'A', 100],
       ['Park', 'B', 80],
       ['Kim', 'A', 90]], dtype=object)

In [32]:
df.columns

Index(['name', 'grade', 'score'], dtype='str')

In [25]:
df['name'].values

<StringArray>
['Lee', 'Park', 'Kim']
Length: 3, dtype: str

In [40]:
df.loc[1, 'name']

'Park'

### DataFrame과 리스트, 딕셔너리, 넘파이 dnarray간의 상호 변환<br>
```txt
1. 리스트 -> 데이터 프레임
-> df = pd.DataFrame(list, columns=col_name)
<- DataFrame의 values속성을 이용하여 ndarray 변환: tolist()
2. 딕셔너리 -> 데이터 프레임
-> dict = {'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33],}
df = pd.DataFrame(dict)
<- 데이터프레임이 저공하는 to_dict()
3. Numpy ndarray -> 데이터 프레임
-> df = pd.DataFrame(array, columns=col_name)
<- 데이터프레임 객체의 values속성을 이용하여 ndarray변환
```

#### STEP1#1 리스트를 이용한 DataFrame생성

In [26]:
data = [['Lee', 100, 'A'],
      ['Park', 80, 'B'],
      ['Kim', 90, 'A']]
df = pd.DataFrame(data, columns=['name', 'score', 'grade'])
df

   name  score grade
0   Lee    100     A
1  Park     80     B
2   Kim     90     A

STEP#1-2 DataFrame을 리스트로 변환

In [28]:
df.values.tolist()

[['Lee', 100, 'A'], ['Park', 80, 'B'], ['Kim', 90, 'A']]

STEP#2-1 딕셔너리를 이용한 DataFrame생성

In [29]:
data = {
  'name': ['Lee', 'Park', 'Kim'],
  'score': [100, 80, 90],
  'grade': ['A', 'B', 'A']
}
# import pandas as pd
df = pd.DataFrame(data, columns=['name', 'grade', 'score'])
df
# print(df.__class__)
# print(type(pd))

   name grade  score
0   Lee     A    100
1  Park     B     80
2   Kim     A     90

STEP#2-2 DataFrame을 딕셔너리로 변환

In [30]:
df.to_dict()
# print(type(df))

{'name': {0: 'Lee', 1: 'Park', 2: 'Kim'},
 'grade': {0: 'A', 1: 'B', 2: 'A'},
 'score': {0: 100, 1: 80, 2: 90}}

STEP#3-1 ndarray를 이용한 DataFrame생성

In [ ]:
import numpy as np
array = np.array([['Lee', 100, 'A'],
      ['Park', 80, 'B'],
      ['Kim', 90, 'A']])
df = pd.DataFrame(data, columns=['name', 'score', 'grade'])
df

# print(type(df))

<class 'pandas.DataFrame'>

STEP#3-2 DataFrame을 ndarray로 변환

In [73]:
df.values
# print(type(df))

array([['Lee', 100, 'A'],
       ['Park', 80, 'B'],
       ['Kim', 90, 'A']], dtype=object)

### 데이터 셀렉션 및 필터링
```txt
1. [] : 컬럼 기반 필터링 또는 불린 인덱싱 필터링 제공
  (예:) df.컬럼명, df['컬럼명'], df[1:3], df[:2]
2. loc[인덱스명, 컬럼명] - 명칭 기반 인덱싱
  Index명, column명 기준으로 데이터가 조회
    예:) 하나의 행 검색 : df.loc[0]
        여러 행 검색 : df.loc[[0,1]]
        여러 행과 열 검색 : df.loc[0:2, ['score','grade']]
3. iloc[인덱스, 컬럼인덱스] - 위치기반 인덱싱
  0을 출발점으로 하는 가로축, 세로축 좌표 기반의 행과 열 위치를 기반으로 데이터를 지정
  행,열 위치 값으로 정수를 사용할 수 있음
  주의: 오직 인덱스를 기준으로 데이터를 가져옴. 인덱스가 순서를 의미하지 않음
    예:) df.iloc[0:3], df.iloc[3], df.iloc[0:3, 0:2]
4. 불린(Boolean)인덱싱
  위치 기반, 명칭 기반 인덱싱 모두 사용할 필요없이 조건식을 []안에 기입하여 필터링함
    예:) df.loc[df['score']>90], df.loc[df['grade'] == 'B']
```

In [31]:
# []
data = {
  'name': ['Lee', 'Park', 'Kim'],
  'score': [100, 80, 90],
  'grade': ['A', 'B', 'A']
}
# import pandas as pd
df = pd.DataFrame(data, columns=['name', 'grade', 'score'])
df

   name grade  score
0   Lee     A    100
1  Park     B     80
2   Kim     A     90

In [75]:
# 하나의 컬럼 검색
df.name

0     Lee
1    Park
2     Kim
Name: name, dtype: str

In [32]:
# 2개 이상의 컬럼 검색
df[['name', 'grade']]

   name grade
0   Lee     A
1  Park     B
2   Kim     A

명칭 기반 인덱싱 -loc[ 인덱스명, 컬럼명 ]

In [80]:
# 하나의 행 검색
df.loc[0]

name     Lee
grade      A
score    100
Name: 0, dtype: object

In [81]:
df.loc[[0, 2]]

  name grade  score
0  Lee     A    100
2  Kim     A     90

In [82]:
# 여러 행 검색
df.loc[0 : 2]

   name grade  score
0   Lee     A    100
1  Park     B     80
2   Kim     A     90

In [91]:
# 여러 행과 열 검색
df.loc[0:2, ['score', 'grade']]

   score grade
0    100     A
1     80     B
2     90     A

위치 기반 인덱싱 - iloc[인덱스, 컬럼인덱스]

In [94]:
df.iloc[0: 3]

   name grade  score
0   Lee     A    100
1  Park     B     80
2   Kim     A     90

In [ ]:
# 인덱스 임계 숫자는 포함, 컬럼 인덱스 임계는 미포함
df.iloc[0:3, 0:2]

   name grade
0   Lee     A
1  Park     B
2   Kim     A

In [ ]:
# 유효하지 않음 인덱스값은 에러를 발생시킴
df.iloc[3]

IndexError: single positional indexer is out-of-bounds

불린 인덱싱

In [100]:
df.loc[df['score'] > 90]

  name grade  score
0  Lee     A    100

In [102]:
df.loc[df['grade'] == 'A']

  name grade  score
0  Lee     A    100
2  Kim     A     90

DataFrame 데이터 추가<br>
DataFrame 데이터 삭제<br>
1. drop()
- DataFrame.drop(labels=None, axis=0, index=None, columns=none, inplace=False)
- axis: DataFrame의 로우를 삭제할 때는 axis=0, 컬럼을 삭제할 때는 axis=1
- 원본 DataFrame에 사게된 결과를 적용할 경우에는 inplace=True적용
2. del df['컬럼명']

In [103]:
df.drop(index=1)  # drop() 실제로 삭제되지 않음
df

   name grade  score
0   Lee     A    100
1  Park     B     80
2   Kim     A     90

In [104]:
df

   name grade  score
0   Lee     A    100
1  Park     B     80
2   Kim     A     90

In [105]:
df_new = df.drop(index=1)
df_new

  name grade  score
0  Lee     A    100
2  Kim     A     90

In [ ]:
# drop()
df.drop(index=5)

KeyError: '[5] not found in axis'

In [110]:
del df['grade']   # 실제로 배열에서 빠짐
df

KeyError: 'grade'

In [112]:
# df
df

   name  score
0   Lee    100
1  Park     80
2   Kim     90